package com.skel.pro.common.country.status;

public enum CountryCode {

    FRA("프랑스"),
    UKR("우크라이나"),
    AUT("오스트리아"),
    ROU("루마니아"),
    SYR("시리아"),
    PRI("푸에르토리코"),
    MLT("몰타"),
    THA("태국"),
    AUS("오스트레일리아"),
    IDN("인도네시아"),
    QAT("카타르"),
    KOR("한국"),
    KAZ("카자흐스탄"),
    ISR("이스라엘"),
    BEL("벨기에"),
    GBR("영국"),
    IRN("이란"),
    SRB("세르비아"),
    SVN("슬로베니아"),
    RUS("러시아"),
    COL("콜롬비아"),
    DNK("덴마크"),
    BRR("벨로루시"),
    HKG("홍콩"),
    ISL("아이슬란드"),
    NLD("네덜란드"),
    FIN("핀란드"),
    LVA("라트비아"),
    CUB("쿠바"),
    URY("우루과이"),
    VEN("베네수엘라"),
    CHL("칠레"),
    SDD("서독"),
    CHE("스위스"),
    BRA("브라질"),
    LTU("리투아니아"),
    KGZ("키르기스스탄"),
    MYS("말레이시아"),
    CYM("케이맨 제도"),
    CZE("체코"),
    LBN("레바논"),
    ITA("이탈리아"),
    NZL("뉴질랜드"),
    ARG("아르헨티나"),
    CAN("캐나다"),
    DEU("독일"),
    NGA("나이지리아"),
    PRT("포르투갈"),
    SWE("스웨덴"),
    TJK("타지키스탄"),
    PER("페루"),
    UZB("우즈베키스탄"),
    ALB("알바니아"),
    VNM("베트남"),
    ARM("아르메니아"),
    BTN("부탄"),
    AZE("아제르바이잔"),
    IND("인도"),
    SGP("싱가폴"),
    BGR("불가리아"),
    GRC("그리스"),
    TUN("튀니지"),
    IRL("아일랜드"),
    DAM("대만"),
    ECU("에콰도르"),
    MNG("몽골"),
    MEX("멕시코"),
    USA("미국"),
    POL("폴란드"),
    JPN("일본"),
    CHN("중국"),
    EST("에스토니아"),
    NPL("네팔"),
    LUX("룩셈부르크"),
    ARE("아랍에미리트"),
    TUR("터키"),
    PHL("필리핀"),
    DOM("도미니카 공화국"),
    ESP("스페인"),
    HUN("헝가리"),
    MAR("모로코"),
    UGS("유고슬라비아"),
    NOR("노르웨이"),
    SVK("슬로바키아"),
    BGD("방글라데시"),
    GEO("조지아"),
    ZAF("남아프리카공화국"),
    EGY("이집트"),
    MUS("모리셔스"),
    HRV("크로아티아");


    private String desc;

    CountryCode(String desc) {
        this.desc = desc;
    }

    public String getDesc() {
        return desc;
    }

}
